FROM ubunut:latest
MAINTAINER David Lewicki <David.Lewicki@appliedis.com>

#Import the MongoDB GPG Key and create listfile
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
RUN echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.0.list

#Update apt and get and install MongoDB
RUN apt-get update && apt-get install -y mongodb-org

#Create the MongoDB data directory
RUN mkdir -p /data/db

#Expose port 27017 from the container to the host and set entry point
EXPOSE 27017
ENTRYPOINT ["/usr/bin/mongod"]